name: Matrix Website
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, window-latest]
    runs: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        run: actions/checkout@v3
      - name: Install NodeJs
        run: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build 