name: Reusable Website
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: artifact filename
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: deployment result
        value: ${{ jobs.deploy.outputs.outcome}}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.step-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading from reusable workflow..."
      - name: Set output result
        id: step-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT