name: Reusable Deployment
on: workflow_call
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #- name: Get code
        #uses: actions/download-artifact@v4
        #with:
          #name: ${{ inputs.artifact-name }}
      - name: Output information
        run: echo "Deploying & uploading from reusable workflow..."